- name: Create AMI and Save it For Later
  hosts: masters
  connection: local
  gather_facts: yes
  tasks:

    - name: Create Instance
      ec2: 
        region: "{{ aws.region.geo }}"
        key_name: "{{ aws.ec2.key_name }}"
        instance_type: "{{ aws.ec2.masters.instance_type }}"
        image: "{{ aws.ec2.base }}"
        wait: yes
        groups: "{{ aws.ec2.masters.security_group }}"
        vpc_subnet_id: "{{ aws.ec2.vpc_id }}"
        instance_tags:
          Name: "{{ inventory_hostname }}"
        count_tag:
          Name: "{{ inventory_hostname }}"
        exact_count: 1
        volumes: "{{ aws.ec2.masters.volumes }}"
      register: master

    - name: Assign IP to Host
      set_fact:
        ansible_host: "{{ master.tagged_instances[0].private_ip }}"
        instance_id: "{{ master.tagged_instances[0].id }}"


- name: Create AMI and Save it For Later
  hosts: masters
  serial: 1
  become: yes
  roles:
    # - role: elasticsearch
    #   vars:
    #     action: configure
    #     job: master
  tasks:

    - service:
        name: elasticsearch
        state: restarted