---

- name: Install Docker Repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: yes

- name: Install Docker-CE
  yum:
    update_cache: yes
    name: docker-ce
  become: yes

- name: Start and Enable Docker Service
  service:
    name: docker
    state: reloaded
    enabled: yes
  become: yes