---

# placed here to simply ensure that the correct config is 
# sent / updated
# - shell: rm -rf /etc/elasticsearch/*

- name: Sync Standard Config Files
  copy:
    src: config/
    dest: /etc/elasticsearch
    
- name: Make sure permissions are right
  file: 
    path: "{{ item }}"
    recurse: yes
    owner: 997
    group: 993
    mode: 0777
  with_items:
    - /etc/elasticsearch
    - /usr/share/elasticsearch

- name: set vm.max_map_count to 262144 in sysctl
  sysctl: name={{ item.key }} value={{ item.value }}
  with_items:
    - { key: "vm.max_map_count", value: "262144" }

- name: Write Template
  template:
    src: ./templates/elastic.yml
    dest: /etc/elasticsearch/elasticsearch.yml
  notify:
        - restart_elastic
